org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# Override for physical device; default emulator URL is used when this is absent
SD_API_BASE_URL=https://scripture-daily.onrender.com/api/v1/
#SD_API_BASE_URL=http://10.0.2.2:8000/api/v1/
#SD_API_BASE_URL=http://192.168.1.20:8000/api/v1/
